services:
    app:
        build: .
        container_name: fixit-project-dev
        hostname: fixit_backend
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules

        command: nodemon --legacy-watch --inspect=0.0.0.0 index.js
        environment:
            - NODE_ENV=development
    postgres:
        image: postgres:latest
        container_name: fixit_db_container
        hostname: fixit_db
        restart: always
        env_file:
            - postgres.env
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
        driver: local
